language: java
jdk:
  - openjdk8
before_install:
 - chmod +x ./tictactoebot/gradlew
 - chmod +x ./tictactoeclient/gradlew
 - chmod +x ./tictactoeserver/gradlew
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
 - ./tictactoebot/gradlew assemble
 - ./tictactoebot/gradlew test
 - ./tictactoeclient/gradlew assemble
 - ./tictactoeclient/gradlew test
 - ./tictactoeserver/gradlew assemble
 - ./tictactoeserver/gradlew test
